'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Soapy
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Soapy.TPReadOnlyDataServiceSoap")>  _
    Public Interface TPReadOnlyDataServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntities", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function findEntities(ByVal username As String, ByVal password As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntities", ReplyAction:="*")>  _
        Function findEntitiesAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntitiesBySchoolID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function findEntitiesBySchoolID(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntitiesBySchoolID", ReplyAction:="*")>  _
        Function findEntitiesBySchoolIDAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntitiesBySchoolIDAsXml", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function findEntitiesBySchoolIDAsXml(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/findEntitiesBySchoolIDAsXml", ReplyAction:="*")>  _
        Function findEntitiesBySchoolIDAsXmlAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getEntityData(ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityData", ReplyAction:="*")>  _
        Function getEntityDataAsync(ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityDataBySchoolID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getEntityDataBySchoolID(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityDataBySchoolID", ReplyAction:="*")>  _
        Function getEntityDataBySchoolIDAsync(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityDataBySchoolIDAsXml", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getEntityDataBySchoolIDAsXml(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEntityDataBySchoolIDAsXml", ReplyAction:="*")>  _
        Function getEntityDataBySchoolIDAsXmlAsync(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getExcelAddInData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getExcelAddInData(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal columns As String, ByVal domain As String, ByVal filters As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getExcelAddInData", ReplyAction:="*")>  _
        Function getExcelAddInDataAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal columns As String, ByVal domain As String, ByVal filters As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getExcelAddInColumns", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getExcelAddInColumns(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal domain As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getExcelAddInColumns", ReplyAction:="*")>  _
        Function getExcelAddInColumnsAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal domain As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/validateExcelAddInAccount", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validateExcelAddInAccount(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/validateExcelAddInAccount", ReplyAction:="*")>  _
        Function validateExcelAddInAccountAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getFMS6Data", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getFMS6Data(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal dataRequestType As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getFMS6Data", ReplyAction:="*")>  _
        Function getFMS6DataAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal dataRequestType As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/testDatabaseConnection", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function testDatabaseConnection(ByVal schoolID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/testDatabaseConnection", ReplyAction:="*")>  _
        Function testDatabaseConnectionAsync(ByVal schoolID As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TPReadOnlyDataServiceSoapChannel
        Inherits Soapy.TPReadOnlyDataServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TPReadOnlyDataServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Soapy.TPReadOnlyDataServiceSoap)
        Implements Soapy.TPReadOnlyDataServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function findEntities(ByVal username As String, ByVal password As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.findEntities
            Return MyBase.Channel.findEntities(username, password)
        End Function
        
        Public Function findEntitiesAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.findEntitiesAsync
            Return MyBase.Channel.findEntitiesAsync(username, password)
        End Function
        
        Public Function findEntitiesBySchoolID(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.findEntitiesBySchoolID
            Return MyBase.Channel.findEntitiesBySchoolID(schoolID, username, password)
        End Function
        
        Public Function findEntitiesBySchoolIDAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.findEntitiesBySchoolIDAsync
            Return MyBase.Channel.findEntitiesBySchoolIDAsync(schoolID, username, password)
        End Function
        
        Public Function findEntitiesBySchoolIDAsXml(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As String Implements Soapy.TPReadOnlyDataServiceSoap.findEntitiesBySchoolIDAsXml
            Return MyBase.Channel.findEntitiesBySchoolIDAsXml(schoolID, username, password)
        End Function
        
        Public Function findEntitiesBySchoolIDAsXmlAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String) Implements Soapy.TPReadOnlyDataServiceSoap.findEntitiesBySchoolIDAsXmlAsync
            Return MyBase.Channel.findEntitiesBySchoolIDAsXmlAsync(schoolID, username, password)
        End Function
        
        Public Function getEntityData(ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.getEntityData
            Return MyBase.Channel.getEntityData(entityName, entityFilter, username, password)
        End Function
        
        Public Function getEntityDataAsync(ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.getEntityDataAsync
            Return MyBase.Channel.getEntityDataAsync(entityName, entityFilter, username, password)
        End Function
        
        Public Function getEntityDataBySchoolID(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.getEntityDataBySchoolID
            Return MyBase.Channel.getEntityDataBySchoolID(schoolID, entityName, entityFilter, username, password)
        End Function
        
        Public Function getEntityDataBySchoolIDAsync(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.getEntityDataBySchoolIDAsync
            Return MyBase.Channel.getEntityDataBySchoolIDAsync(schoolID, entityName, entityFilter, username, password)
        End Function
        
        Public Function getEntityDataBySchoolIDAsXml(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As String Implements Soapy.TPReadOnlyDataServiceSoap.getEntityDataBySchoolIDAsXml
            Return MyBase.Channel.getEntityDataBySchoolIDAsXml(schoolID, entityName, entityFilter, username, password)
        End Function
        
        Public Function getEntityDataBySchoolIDAsXmlAsync(ByVal schoolID As Integer, ByVal entityName As String, ByVal entityFilter As String, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String) Implements Soapy.TPReadOnlyDataServiceSoap.getEntityDataBySchoolIDAsXmlAsync
            Return MyBase.Channel.getEntityDataBySchoolIDAsXmlAsync(schoolID, entityName, entityFilter, username, password)
        End Function
        
        Public Function getExcelAddInData(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal columns As String, ByVal domain As String, ByVal filters As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.getExcelAddInData
            Return MyBase.Channel.getExcelAddInData(schoolID, username, password, columns, domain, filters)
        End Function
        
        Public Function getExcelAddInDataAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal columns As String, ByVal domain As String, ByVal filters As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.getExcelAddInDataAsync
            Return MyBase.Channel.getExcelAddInDataAsync(schoolID, username, password, columns, domain, filters)
        End Function
        
        Public Function getExcelAddInColumns(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal domain As String) As System.Data.DataSet Implements Soapy.TPReadOnlyDataServiceSoap.getExcelAddInColumns
            Return MyBase.Channel.getExcelAddInColumns(schoolID, username, password, domain)
        End Function
        
        Public Function getExcelAddInColumnsAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal domain As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Soapy.TPReadOnlyDataServiceSoap.getExcelAddInColumnsAsync
            Return MyBase.Channel.getExcelAddInColumnsAsync(schoolID, username, password, domain)
        End Function
        
        Public Function validateExcelAddInAccount(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As Boolean Implements Soapy.TPReadOnlyDataServiceSoap.validateExcelAddInAccount
            Return MyBase.Channel.validateExcelAddInAccount(schoolID, username, password)
        End Function
        
        Public Function validateExcelAddInAccountAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of Boolean) Implements Soapy.TPReadOnlyDataServiceSoap.validateExcelAddInAccountAsync
            Return MyBase.Channel.validateExcelAddInAccountAsync(schoolID, username, password)
        End Function
        
        Public Function getFMS6Data(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal dataRequestType As String) As String Implements Soapy.TPReadOnlyDataServiceSoap.getFMS6Data
            Return MyBase.Channel.getFMS6Data(schoolID, username, password, dataRequestType)
        End Function
        
        Public Function getFMS6DataAsync(ByVal schoolID As Integer, ByVal username As String, ByVal password As String, ByVal dataRequestType As String) As System.Threading.Tasks.Task(Of String) Implements Soapy.TPReadOnlyDataServiceSoap.getFMS6DataAsync
            Return MyBase.Channel.getFMS6DataAsync(schoolID, username, password, dataRequestType)
        End Function
        
        Public Function testDatabaseConnection(ByVal schoolID As Integer) As Boolean Implements Soapy.TPReadOnlyDataServiceSoap.testDatabaseConnection
            Return MyBase.Channel.testDatabaseConnection(schoolID)
        End Function
        
        Public Function testDatabaseConnectionAsync(ByVal schoolID As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements Soapy.TPReadOnlyDataServiceSoap.testDatabaseConnectionAsync
            Return MyBase.Channel.testDatabaseConnectionAsync(schoolID)
        End Function
    End Class
End Namespace
